# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fastimage` gem.
# Please instead update this file by running `bin/tapioca gem fastimage`.


# pkg:gem/fastimage#lib/fastimage/fastimage.rb:22
class FastImage
  include ::FastImageParsing

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:185
  def initialize(uri, options = T.unsafe(nil)); end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:226
  def animated; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:25
  def bytes_read; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:232
  def content_length; end

  # find an appropriate method to fetch the image according to the passed parameter
  #
  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:239
  def fetch; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:222
  def height; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:213
  def orientation; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:201
  def size; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:195
  def type; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:218
  def width; end

  private

  # Some invalid locations need escaping
  #
  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:283
  def escaped_location(location); end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:416
  def fetch_using_base64(uri); end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:408
  def fetch_using_file_open; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:276
  def fetch_using_http; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:293
  def fetch_using_http_from_parsed_uri; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:379
  def fetch_using_read(readable); end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:468
  def parse_animated; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:426
  def parse_packets(stream); end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:464
  def parse_size; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:458
  def parser_class; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:348
  def protocol_relative_url?(url); end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:352
  def proxy_uri; end

  # pkg:gem/fastimage#lib/fastimage/fastimage.rb:365
  def setup_http; end

  class << self
    # Returns a boolean value indicating the image is animated.
    # It will return nil if the image could not be fetched, or if the image type was not recognised.
    #
    # By default there is a timeout of 2 seconds for opening and reading from a remote server.
    # This can be changed by passing a :timeout => number_of_seconds in the options.
    #
    # If you wish FastImage to raise if it cannot find the type of the image for any reason, then pass
    # :raise_on_failure => true in the options.
    #
    # === Example
    #
    #   require 'fastimage'
    #
    #   FastImage.animated?("test/fixtures/test.gif")
    #   => false
    #   FastImage.animated?("test/fixtures/animated.gif")
    #   => true
    #
    # === Supported options
    # [:timeout]
    #   Overrides the default timeout of 2 seconds.  Applies both to reading from and opening the http connection.
    # [:raise_on_failure]
    #   If set to true causes an exception to be raised if the image type cannot be found for any reason.
    #
    # pkg:gem/fastimage#lib/fastimage/fastimage.rb:181
    def animated?(uri, options = T.unsafe(nil)); end

    # Returns an array containing the width and height of the image.
    # It will return nil if the image could not be fetched, or if the image type was not recognised.
    #
    # By default there is a timeout of 2 seconds for opening and reading from a remote server.
    # This can be changed by passing a :timeout => number_of_seconds in the options.
    #
    # If you wish FastImage to raise if it cannot size the image for any reason, then pass
    # :raise_on_failure => true in the options.
    #
    # FastImage knows about GIF, JPEG, BMP, TIFF, ICO, CUR, PNG, HEIC/HEIF, AVIF, PSD, SVG, WEBP and JXL files.
    #
    # === Example
    #
    #   require 'fastimage'
    #
    #   FastImage.size("https://switchstep.com/images/ios.gif")
    #   => [196, 283]
    #   FastImage.size("http://switchstep.com/images/ss_logo.png")
    #   => [300, 300]
    #   FastImage.size("https://upload.wikimedia.org/wikipedia/commons/0/09/Jpeg_thumb_artifacts_test.jpg")
    #   => [1280, 800]
    #   FastImage.size("https://eeweb.engineering.nyu.edu/~yao/EL5123/image/lena_gray.bmp")
    #   => [512, 512]
    #   FastImage.size("test/fixtures/test.jpg")
    #   => [882, 470]
    #   FastImage.size("http://switchstep.com/does_not_exist")
    #   => nil
    #   FastImage.size("http://switchstep.com/does_not_exist", :raise_on_failure=>true)
    #   => raises FastImage::ImageFetchFailure
    #   FastImage.size("http://switchstep.com/images/favicon.ico", :raise_on_failure=>true)
    #   => [16, 16]
    #   FastImage.size("http://switchstep.com/foo.ics", :raise_on_failure=>true)
    #   => raises FastImage::UnknownImageType
    #   FastImage.size("http://switchstep.com/images/favicon.ico", :raise_on_failure=>true, :timeout=>0.01)
    #   => raises FastImage::ImageFetchFailure
    #   FastImage.size("http://switchstep.com/images/faulty.jpg", :raise_on_failure=>true)
    #   => raises FastImage::SizeNotFound
    #
    # === Supported options
    # [:timeout]
    #   Overrides the default timeout of 2 seconds.  Applies both to reading from and opening the http connection.
    # [:raise_on_failure]
    #   If set to true causes an exception to be raised if the image size cannot be found for any reason.
    #
    # pkg:gem/fastimage#lib/fastimage/fastimage.rb:111
    def size(uri, options = T.unsafe(nil)); end

    # Returns an symbol indicating the image type fetched from a uri.
    # It will return nil if the image could not be fetched, or if the image type was not recognised.
    #
    # By default there is a timeout of 2 seconds for opening and reading from a remote server.
    # This can be changed by passing a :timeout => number_of_seconds in the options.
    #
    # If you wish FastImage to raise if it cannot find the type of the image for any reason, then pass
    # :raise_on_failure => true in the options.
    #
    # === Example
    #
    #   require 'fastimage'
    #
    #   FastImage.type("https://switchstep.com/images/ios.gif")
    #   => :gif
    #   FastImage.type("http://switchstep.com/images/ss_logo.png")
    #   => :png
    #   FastImage.type("https://upload.wikimedia.org/wikipedia/commons/0/09/Jpeg_thumb_artifacts_test.jpg")
    #   => :jpeg
    #   FastImage.type("https://eeweb.engineering.nyu.edu/~yao/EL5123/image/lena_gray.bmp")
    #   => :bmp
    #   FastImage.type("test/fixtures/test.jpg")
    #   => :jpeg
    #   FastImage.type("http://switchstep.com/does_not_exist")
    #   => nil
    #   File.open("/some/local/file.gif", "r") {|io| FastImage.type(io)}
    #   => :gif
    #   FastImage.type("test/fixtures/test.tiff")
    #   => :tiff
    #   FastImage.type("test/fixtures/test.psd")
    #   => :psd
    #
    # === Supported options
    # [:timeout]
    #   Overrides the default timeout of 2 seconds.  Applies both to reading from and opening the http connection.
    # [:raise_on_failure]
    #   If set to true causes an exception to be raised if the image type cannot be found for any reason.
    #
    # pkg:gem/fastimage#lib/fastimage/fastimage.rb:153
    def type(uri, options = T.unsafe(nil)); end
  end
end

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:37
class FastImage::BadImageURI < ::FastImage::FastImageException; end

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:35
class FastImage::CannotParseImage < ::FastImage::FastImageException; end

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:40
FastImage::DefaultTimeout = T.let(T.unsafe(nil), Integer)

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:27
class FastImage::FastImageException < ::StandardError; end

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:31
class FastImage::ImageFetchFailure < ::FastImage::FastImageException; end

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:42
FastImage::LocalFileChunkSize = T.let(T.unsafe(nil), Integer)

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:46
FastImage::Parsers = T.let(T.unsafe(nil), Hash)

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:65
FastImage::SUPPORTED_IMAGE_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:33
class FastImage::SizeNotFound < ::FastImage::FastImageException; end

# pkg:gem/fastimage#lib/fastimage/fastimage.rb:29
class FastImage::UnknownImageType < ::FastImage::FastImageException; end

# pkg:gem/fastimage#lib/fastimage/version.rb:4
FastImage::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/image_base.rb:1
module FastImageParsing
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:67
  def parse_size_for_jxl; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/avif.rb:2
class FastImageParsing::Avif < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/avif.rb:8
  def animated?; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/avif.rb:3
  def dimensions; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/bmp.rb:2
class FastImageParsing::Bmp < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/bmp.rb:3
  def dimensions; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/exif.rb:2
class FastImageParsing::Exif
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/exif.rb:5
  def initialize(stream); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/exif.rb:3
  def height; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/exif.rb:3
  def orientation; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/exif.rb:11
  def rotated?; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/exif.rb:3
  def width; end

  private

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/exif.rb:17
  def get_exif_byte_order; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/exif.rb:57
  def parse_exif; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/exif.rb:29
  def parse_exif_ifd; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/fiber_stream.rb:2
class FastImageParsing::FiberStream
  include ::FastImageParsing::StreamUtil

  # read_fiber should return nil if it no longer has anything to return when resumed
  # so the result of the whole Fiber block should be set to be nil in case yield is no
  # longer called
  #
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/fiber_stream.rb:9
  def initialize(read_fiber); end

  # Peeking beyond the end of the input will raise
  #
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/fiber_stream.rb:17
  def peek(n); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/fiber_stream.rb:4
  def pos; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/fiber_stream.rb:33
  def read(n); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/fiber_stream.rb:40
  def skip(n); end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/gif.rb:2
class FastImageParsing::Gif < ::FastImageParsing::ImageBase
  # Checks for multiple frames
  #
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/gif.rb:8
  def animated?; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/gif.rb:3
  def dimensions; end

  private

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/gif.rb:52
  def skip_sub_blocks; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/heic.rb:2
class FastImageParsing::Heic < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/heic.rb:3
  def dimensions; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jpeg.rb:2
class FastImageParsing::IOStream < ::SimpleDelegator
  include ::FastImageParsing::StreamUtil
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/ico.rb:2
class FastImageParsing::Ico < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/ico.rb:3
  def dimensions; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/image_base.rb:2
class FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/image_base.rb:3
  def initialize(stream); end

  # Implement in subclasses if appropriate
  #
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/image_base.rb:13
  def animated?; end

  # Implement in subclasses
  #
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/image_base.rb:8
  def dimensions; end
end

# HEIC/AVIF are a special case of the general ISO_BMFF format, in which all data is encapsulated in typed boxes,
# with a mandatory ftyp box that is used to indicate particular file types. Is composed of nested "boxes". Each
# box has a header composed of
# - Size (32 bit integer)
# - Box type (4 chars)
# - Extended size: only if size === 1, the type field is followed by 64 bit integer of extended size
# - Payload: Type-dependent
#
# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:9
class FastImageParsing::IsoBmff
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:12
  def initialize(stream); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:10
  def height; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:18
  def parse_isobmff; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:10
  def width; end

  private

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:91
  def handle_hdlr_box(box_size); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:98
  def handle_ipma_box(box_size); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:79
  def handle_irot_box; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:83
  def handle_ispe_box(box_size, index); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:147
  def handle_jxlc_box(box_size); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:124
  def handle_meta_box(box_size); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:119
  def handle_pitm_box(box_size); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:153
  def read_box_header!; end

  # If you need to inspect a heic/heif file, use
  # https://gpac.github.io/mp4box.js/test/filereader.html
  #
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:43
  def read_boxes!(max_read_bytes = T.unsafe(nil)); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:164
  def read_uint16!; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:168
  def read_uint32!; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:172
  def read_uint64!; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/iso_bmff.rb:160
  def read_uint8!; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jpeg.rb:6
class FastImageParsing::Jpeg < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jpeg.rb:7
  def dimensions; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxl.rb:2
class FastImageParsing::Jxl < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxl.rb:3
  def dimensions; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:2
class FastImageParsing::Jxlc
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:8
  def initialize(stream); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:40
  def get_bits(size); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:3
  def height; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:15
  def parse_jxlc; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:3
  def width; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:57
  def x_from_ratio(y); end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:5
FastImageParsing::Jxlc::LENGTHS = T.let(T.unsafe(nil), Array)

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/jxlc.rb:6
FastImageParsing::Jxlc::MULTIPLIERS = T.let(T.unsafe(nil), Array)

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/png.rb:2
class FastImageParsing::Png < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/png.rb:7
  def animated?; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/png.rb:3
  def dimensions; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/psd.rb:2
class FastImageParsing::Psd < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/psd.rb:3
  def dimensions; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/stream_util.rb:2
module FastImageParsing::StreamUtil
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/stream_util.rb:3
  def read_byte; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/stream_util.rb:7
  def read_int; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/stream_util.rb:11
  def read_string_int; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/svg.rb:2
class FastImageParsing::Svg < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/svg.rb:3
  def dimensions; end

  private

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/svg.rb:59
  def attr_value; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/svg.rb:23
  def parse_svg; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/tiff.rb:2
class FastImageParsing::Tiff < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/tiff.rb:3
  def initialize(stream); end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/tiff.rb:7
  def dimensions; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/type_parser.rb:2
class FastImageParsing::TypeParser
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/type_parser.rb:3
  def initialize(stream); end

  # type will use peek to get enough bytes to determing the type of the image
  #
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/type_parser.rb:8
  def type; end
end

# pkg:gem/fastimage#lib/fastimage/fastimage_parsing/webp.rb:2
class FastImageParsing::Webp < ::FastImageParsing::ImageBase
  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/webp.rb:18
  def animated?; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/webp.rb:3
  def dimensions; end

  private

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/webp.rb:36
  def parse_size_vp8; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/webp.rb:41
  def parse_size_vp8l; end

  # pkg:gem/fastimage#lib/fastimage/fastimage_parsing/webp.rb:47
  def parse_size_vp8x; end
end
